[package]
name = "eko"
version = "0.1.0"
edition = "2021"
description = "An echo clone to test clap :)"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.10", features = ["derive"] }
